settings:
  title: 'BaryonBib Status'
  url: 'https://status.baryonbib.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www.baryonbib.org # unique identifier
    name: BaryonBib Web
    description: 'www.baryonbib.org' # default=empty
    url: 'https://www.baryonbib.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api.baryonics.org
    name: Baryonics API
    description: 'api.baryonics.org'
    url: 'https://api.baryonics.org/prod/v1'
    method: GET
    expectStatus: 200
    linkable: false

  - id: core.baryonbib.org
    name: BaryonBib Core
    description: 'core.baryonbib.org'
    url: 'https://core.baryonbib.org/prod/v1'
    method: GET
    expectStatus: 200
    linkable: false

  - id: www.baryonid.com
    name: BaryonID
    description: 'www.baryonid.com'
    url: 'https://www.baryonid.com/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: partnership.baryonbib.com
    name: Partnership Portal
    description: 'partnership.baryonbib.com'
    url: 'https://partnership.baryonbib.com/'
    method: GET
    expectStatus: 200

  - id: events.baryonbib.com
    name: Events Portal
    description: 'events.baryonbib.com'
    url: 'https://events.baryonbib.com/'
    method: GET
    expectStatus: 200

  - id: reports.baryonbib.com
    name: Baryon Reports Database
    description: 'reports.baryonbib.com'
    url: 'https://reports.baryonbib.com/'
    method: GET
    expectStatus: 200

  - id: admin.baryonbib.com
    name: Subscription Admin Portal
    description: 'admin.baryonbib.com'
    url: 'https://admin.baryonbib.com/'
    method: GET
    expectStatus: 200

  - id: transparency.baryonbib.com
    name: Transparency Report
    description: 'transparency.baryonbib.com'
    url: 'https://transparency.baryonbib.com/'
    method: GET
    expectStatus: 200

  - id: beta.baryonbib.com
    name: BaryonBib Web Beta
    description: 'beta.baryonbib.com'
    url: 'https://beta.baryonbib.com/'
    method: GET
    expectStatus: 200
    linkable: false

### in-app sub-services
  - id: www.baryonbib.org/discover
    name: Discover Service
    description: 'Discover service provides discovery and recommendations for scientific papers, reading lists, research topics, scholars, journals, and books.'
    url: 'https://www.baryonbib.org/discover'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/search
    name: Search Service
    description: 'Search millions of journal papers, billions of figures in them, thousands of scholars, journals, institutions, reading lists, research topics, and more.'
    url: 'https://www.baryonbib.org/search'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/library
    name: Library Service
    description: 'www.baryonbib.org/library'
    url: 'https://www.baryonbib.org/library'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/writing
    name: Writing Service
    description: 'www.baryonbib.org/writing'
    url: 'https://www.baryonbib.org/writing'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/bms
    name: Bib Metrics
    description: 'Measure the impact of journal papers.'
    url: 'https://www.baryonbib.org/bms'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/bms-scholar
    name: Bib Metrics for Scholar
    description: 'Measure the impact of scholars.'
    url: 'https://www.baryonbib.org/bms-scholar'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/bms-journal
    name: Bib Metrics for Journal
    description: 'Measure the quality of journals.'
    url: 'https://www.baryonbib.org/bms-journal'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/bms-institution
    name: Bib Metrics for Institution
    description: 'Measure the impact of research institutions.'
    url: 'https://www.baryonbib.org/bms-institution'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/open-data
    name: Open Data Service
    description: 'www.baryonbib.org/open-data'
    url: 'https://www.baryonbib.org/open-data'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/open-bibliography
    name: Open Bibliography Service
    description: 'www.baryonbib.org/open-bibliography'
    url: 'https://www.baryonbib.org/open-bibliography'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/open-library
    name: Open Library Service
    description: 'www.baryonbib.org/open-library'
    url: 'https://www.baryonbib.org/open-library'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/community/club
    name: Journal Club Service
    description: 'www.baryonbib.org/community/club'
    url: 'https://www.baryonbib.org/community/club'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: www.baryonbib.org/community/news
    name: BaryonBib News
    description: 'BaryonBib News provides global scientific and technical news, fresh and professionally written.'
    url: 'https://www.baryonbib.org/community/news'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/community/columns
    name: BaryonBib Columns
    description: 'Science communication, done it professionally.'
    url: 'https://www.baryonbib.org/community/columns'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/community/discuss
    name: BaryonBib Discuss
    description: 'Discuss academic paper friendly.'
    url: 'https://www.baryonbib.org/community/discuss'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/community/events
    name: BaryonBib Events
    description: 'Discover academic events: conferences, seminars, workshops etc.'
    url: 'https://www.baryonbib.org/community/events'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/community/jobs
    name: BaryonBib Jobs
    description: 'Discover academic jobs across the world.'
    url: 'https://www.baryonbib.org/community/jobs'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: www.baryonbib.org/community/videos
    name: BaryonBib Videos
    description: 'Discover scientific videos, talk recordings, and more.'
    url: 'https://www.baryonbib.org/community/videos'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true


  - id: www.baryonics.org
    name: Baryonics Website
    description: 'www.baryonics.org'
    url: 'https://www.baryonics.org/'
    method: GET
    expectStatus: 200
    
  - id: search.baryonics.org
    name: Baryonics Search
    description: 'search.baryonics.org'
    url: 'https://search.baryonics.org'
    method: GET
    expectStatus: 200
    linkable: true
    
