name = "baryonbib-status-page"
workers_dev = false
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2022-04-05"

[triggers]
crons = ["*/20 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="", preview_id=""}]
#zone_id="xxx"
#route="xxx"
