name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
kv-namespaces = [{binding="KV_STATUS_PAGE", id="40c3081d6c52483ebbb119c085d68b9a", preview_id=""}]\
#zone_id="xxx"
#route="xxx"
